# Generated by Django 4.0.4 on 2023-06-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_mascota_delete_tipo_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
