# Generated by Django 4.0.4 on 2023-06-26 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_id_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion_Producto',
            fields=[
                ('id_clasificacion_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Clasificación productos',
            },
        ),
        migrations.CreateModel(
            name='Marca_Producto',
            fields=[
                ('id_marca_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Marca productos',
            },
        ),
        migrations.AlterModelOptions(
            name='detalle_boleta',
            options={'verbose_name_plural': 'Detalle Boletas'},
        ),
        migrations.AddField(
            model_name='producto',
            name='clasificacion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.clasificacion_producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.marca_producto'),
            preserve_default=False,
        ),
    ]
