# Generated by Django 4.0.4 on 2023-06-26 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clasificacion_producto_marca_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macro_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Macro categorias',
            },
        ),
        migrations.CreateModel(
            name='Micro_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Micro categorias',
            },
        ),
        migrations.CreateModel(
            name='Mid_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('macro_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.macro_categoria')),
            ],
            options={
                'verbose_name_plural': 'Mid categorias',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.DeleteModel(
            name='Clasificacion_Producto',
        ),
        migrations.DeleteModel(
            name='Marca_Producto',
        ),
        migrations.AddField(
            model_name='micro_categoria',
            name='mid_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mid_categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='macro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.macro_categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='micro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.micro_categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='mid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mid_categoria'),
        ),
    ]
