# Generated by Django 4.0.4 on 2023-06-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_macro_categoria_micro_categoria_mid_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='extra_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
